name: Scheduled Restart

on:
  schedule:
      - cron: '0 */6 * * *' # This schedules the workflow to run every 6 hours

      jobs:
        restart:
            runs-on: ubuntu-latest
                steps:
                      - name: Trigger Main Workflow
                              uses: actions/github-script@v6
                                      with:
                                                script: |
                                                            const workflow_id = 'main-main.yml'; // Ensure this matches the actu   filename
                                                                        const ref = 'main';

                                                                                    await github.rest.actions.createWorkflowDispatch({
                                                                                                  owner: context.repo.owner,
                                                                                                                repo: context.repo.repo,
                                                                                                                              workflow_id: workflow_id,
                                                                                                                                            ref: ref
                                                                                                                                                        });
                                                                                                                                                        
                                                                                                                                                        
                                                                                                                                                        git add .github/workflows/main0.yml
                                                                                                                                                        git commit -m "Add scheduled workflow to restart main workflow every 6 hours"
                                                                                                                                                        git push
                                                                                                                                                        
