name: Run Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Kolkata'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install telebot flask aiogram asyncio

      - name: Grant execute permissions to necessary files
        run: chmod +x *  # Grant execute permissions to the specific script

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run dev container
        run: |
          docker build -f .devcontainer/Dockerfile -t my-dev-container .
          docker run --rm my-dev-container python3 /workflow/Gumnaam/GumnaamGhs.py

      - name: Run Python script
        run: python3 GumnaamGhs.py

      - name: Commit and push changes
        run: |
          git config --local user.email "sukhdevsin.g.h.7.3.4.7.3@gmail.com"
          git config --local user.name "GitHub Actions"
          git add .github/workflows/main.yml
          git commit -m "Add scheduled workflow to restart main workflow every 6 hours" || echo "No changes to commit"
          git push
