name: Run Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Kolkata'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install telebot pymongo certifi flask aiogram asyncio docker

      - name: Grant execute permissions to necessary files
        run: |
         chmod +x *

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run Python script
        run: python3 GumnaamGhs.py

      - name: Commit and push changes
        run: |
          git config --local user.email "sukhdevsin.g.h.7.3.4.7.3@gmail.com"
          git config --local user.name "GitHub Actions"
          git add |
          .github/workflows/main.yml
          Gumnaam/GumnaamGhs.py
          git commit -m "Add scheduled workflow to restart main workflow every 6 hours" || echo "No changes to commit"
          git push


          
