name: Run Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Kolkata'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install MongoDB Tools
        run: |
          # Add MongoDB GPG key
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          
          # Add MongoDB repository
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          
          # Update and install MongoDB tools
          sudo apt-get update
          sudo apt-get install -y mongodb-org-tools

    

      - name: Backup MongoDB
        run: |
          echo "Starting MongoDB backup..."
          mkdir -p ./backup  # Create backup directory if it doesn't exist
          mongodump --uri="${{ secrets.MONGO_URI }}" --out=./backup/mongodb_backup_$(date +%F_%T)

      - name: Upload MongoDB Backup
        uses: actions/upload-artifact@v3
        with:
          name: mongodb-backup
          path: ./backup/

      - name: Install dependencies
        run: |
          pip install telebot pyTelegramBotAPI pymongo aiohttp psutil flask aiogram asyncio

      - name: Grant execute permissions to necessary files
        run: | 
          chmod +x *
          chmod +x GumnaamGhs.py  # Specify the script file instead of all files

      - name: Run Python script
        run: python3 GumnaamGhs.py
        
      - name: Commit and push changes
        run: |
          git config --local user.email "sukhdevsin.g.h.7.3.4.7.3@gmail.com"
          git config --local user.name "GitHub Actions"
          git add .github/workflows/main.yml
          git commit -m "Add scheduled workflow to restart main workflow every 6 hours" || echo "No changes to commit"
          git push
