name: Run Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 999999

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Grant execute permissions to all files
        run: chmod +x *

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install telebot flask aiogram asyncio

      - name: Run Python script
        run: python3 GumnaamGhs.py
