name: Run Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Kolkata'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install MongoDB Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb-clients  # Install MongoDB tools including mongodump
          
      # MongoDB Backup Step
      - name: Backup MongoDB
        run: |
          mkdir -p ./backup  # Create backup directory if it doesn't exist
          mongodump --uri="${{ secrets.MONGO_URI }}" --out=./backup/mongodb_backup_$(date +%F_%T)
      
      # Upload MongoDB Backup to GitHub Artifacts
      - name: Upload MongoDB Backup
        uses: actions/upload-artifact@v3
        with:
          name: mongodb-backup
          path: ./backup/

      - name: Install dependencies
        run: |
          pip install telebot pymongo aiohttp psutil flask aiogram asyncio

      - name: Grant execute permissions to necessary files
        run: chmod +x *  # Grant execute permissions to the specific script

      - name: Run Python script
        run: python3 GumnaamGhs.py
        
      # Commit and push changes (optional)
      - name: Commit and push changes
        run: |
          git config --local user.email "sukhdevsin.g.h.7.3.4.7.3@gmail.com"
          git config --local user.name "GitHub Actions"
          git add .github/workflows/main.yml
          git commit -m "Add scheduled workflow to restart main workflow every 6 hours" || echo "No changes to commit"
          git push


